### ISSUE TITLE
free shipping applies to entire cart, not just applicable products

### ISSUE THREAD

**Issue by fawx** [stephenmcd/cartridge#238]
`DiscountForm` sets a session variable and changes the shipping cost to zero on any cart with a discount code that applies free shipping, even if just to a single product.

**Comment by stephenmcd** [comment]
That's by design.

**Comment by stephenmcd** [comment]
Some more detail on this for anyone else who comes across it - the default shipping handler uses a flat rate shipping fee, so as far as defaults go, shipping is dealt with on a per-order basis, not a per-product basis. Therefore the free shipping flag on a discount gets applied to an entire order rather than an individual product - which would be impossible with a flat rate fee per order anyway.

If you want free shipping to apply on a per product basis, that will mean you need a shipping calculator and handler that works with individual products - at that stage you're writing your own shipping handler, and are at will to do what you like with whatever you expect "free shipping" to mean.

**Comment by fawx** [comment]
thank you for the clarification. after writing it up, I understand now why free shipping per product doesn't make sense until you have a custom shipping handler that needs to account for each product's individual characteristics which only matters once a custom handler is actually implemented.

**Comment by stephenmcd** [comment]
Cool, thanks Adam and sorry for the rushed replies earlier.
